name: lexcore
description: "LexCore is an intelligent legal service platform powered by multi-agent collaboration for legal consultation, document generation, case analysis, and law retrieval."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^17.1.0
  dio: ^5.9.0
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  flutter_markdown: ^0.7.7+1
  share_plus: ^11.1.0
  shimmer: ^3.0.0
  google_fonts: ^6.3.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dependency_overrides:
  shared_preferences_android: 2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/auth/
    - doc/privacy_policy.md
    - doc/user_service.md
